language: node_js

node_js:
  - "8"

sudo: required

before_install:
  - npm install -g codecov

services:
  - docker

script:
  - docker image build -t calvinyap/cps847_a2 .
  #add coverage plan
  - codecov
after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to Docker hub
  - docker push calvinyap/cps847_a2
  - bash <(curl -s https://codecov.io/bash)



deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "cps847_A2"
  env: "Cps847a2-env"
  bucket_name: "elasticbeanstalk-us-east-2-769403617610"
  on:
  branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY